version: '3'
services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_SOCKET_URL: http://localhost:5001/room-management
    volumes:
      - ./web/src:/app/src
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY: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
    volumes:
      - ./backend/src:/app/src
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    depends_on:

      - redis

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
