[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Lloyd Wang <LWANG046@e.ntu.edu.sg>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
