# Use a Node.js base image suitable for development
FROM node:18-alpine AS development

# Set the working directory in the container
WORKDIR /app

# Copy package.json, yarn.lock, package-lock.json, and pnpm-lock.yaml (if they exist)
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

# Determine which package manager to use based on the presence of lock files
RUN \
  if [ -f yarn.lock ]; then yarn install; \
  elif [ -f package-lock.json ]; then npm install; \
  elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm && pnpm install --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

COPY . .

# Expose the port on which your Next.js app will run during development
EXPOSE 3000

# Start your Next.js development server
CMD ["yarn", "dev"]
